int foo1() { return 1; }
int foo2() { return 1; }
int foo3() { return 1; }
int foo4() { return 1; }
int foo5() { return 1; }
int foo6() { return 1; }
int foo7() { return 1; }
int foo8() { return 1; }
int foo9() { return 1; }
int foo10() { return 1; }
int foo11() { return 1; }
int foo12() { return 1; }
int foo13() { return 1; }
int foo14() { return 1; }
int foo15() { return 1; }
int foo16() { return 1; }